### PR TITLE
Add macOS Support

### LINKED ISSUE #25: Add macOS Support
### Description

We currently support iOS and tvOS. We should also support macOS.

### Details

Most of the files will compile as they are now on macOS without change. The bulk of work will be in [the Controls](https://github.com/ustwo/formvalidator-swift/tree/master/Sources/Controls), as these are currently very UIKit centric.

We should include a macOS example as well.

### PR DESCRIPTION
**Pull request by ghost**
Resolves #25 `Add macOS Support`.

### Summary

- Add macOS framework, unit test, example, and ui test targets
- Add macOS (i.e. AppKit based) implementations of the validator controls
- Updates UIKit validator controls to use more modern conventions 
- Update `podspec` for UIKit-based and AppKit-based targets (will update for v2.0 later when we merge v2 into master)
- Updates Gem dependencies
- Organise `Example` folder into `iOS` and `macOS` subfolders to separate out the source code

### Alternatives Considered

I looked at using a common source file for both UIKit and AppKit implementations of UI controls and using a combination of typealiases and `#if os()` to separate the code. This become very messy quickly as the UIKit and AppKit implementations are sufficiently different.

Instead, UIKit and AppKit specific files are suffixed as such in the file name (although the type name is common to allow some code portability). The `podspec` ignores the files based on the suffix, allowing for further expansion of framework dependent (and typically platform dependent) code in other areas of the FormValidator-Swift framework.

### Notes

- Travis CI does not run the macOS UI Test Suite, it only builds it. This is due to an open issue. See https://github.com/travis-ci/travis-ci/issues/7075
- Code coverage as reported by codecov.io has gone down with this PR as Xcode UI Tests from Travis to contribute to codecov.io metric for coverage and most of the new code in the framework is for UI controls. Nor are the macOS UI Tests run on Travis, as stated above. See https://github.com/codecov/example-swift/issues/16 for more details on the codecov.io side of the issue.

### CODE REVIEW

**Comment by arnau** [comment]
I would expect the macOS example to show error messages in a similar way as the iOS examples does. It's an small thing but helps getting a better grasp of the library goals.

screen shot 2017-01-12 at 11 09 54

screen shot 2017-01-12 at 11 11 10

**Comment by ghost** [comment]
@arnau Those are examples and not a part of the actual framework. In both those cases, that is actually the standard, native way to display errors using UIKit/AppKit.

**Comment by arnau** [comment]
Yes, I understand. I guess I was expecting a message "Enter valid email…" in the macOS version the same way I saw it before in the iOS example.

**Comment by ghost** [comment]
@arnau Ah! Good catch.

**Comment by ghost** [comment]
@arnau I double checked. It is displaying the same messages next to the field. It's just that in the macOS example, the alert is covering it up.

screen shot 2017-01-12 at 13 57 38

**Comment by jamaine-ustwo** [comment]
@aamctustwo first of all brilliant port, great work!!!! Always good to see multi-plat thinking!

One minor feature request, if I enter an invalid value say 8 in the "Surname" field : -

image

Then delete the value, the error message still remains : -
image

Can we revalidate the TextField on backspace, or should this be handled by an additional "is empty" validator?

**Comment by ghost** [comment]
@jamaine-ustwo This actually has to do with the implementation of the Condition and is not macOS specific. The validator control does re-evaluate when you backspace it to an empty string.

See:

https://github.com/ustwo/formvalidator-swift/blob/f9f57da3c980130625352fb54c734e385d964720/Sources/Conditions/AlphabeticCondition.swift#L45

Which, in turn, is a holdover from the origin Objective-C implementation:

https://github.com/ustwo/US2FormValidator/blob/dd6f49b912e3205328f9d25bee081247662d2523/US2FormValidationFramework/source/conditions/US2ConditionAlphabetic.m#L36-L37

**Comment by jamaine-ustwo** [comment]
@aamctustwo cool beans, in which case, this looks good to go!!!

**Review by jamaine-ustwo — APPROVED** [review]
Looking good, checked out the demo and framework!!

**Pull request merged**
