### PR TITLE
Support for Xcode 10, iOS 12, tvOS 12 and macOS 10.14 (Mojave).

### PR DESCRIPTION
**Pull request by ghost**
### Summary

Adds support for Xcode 10, iOS 12, tvOS 12 and macOS 10.14 (Mojave).

### Note

- Updates CocoaPods to `1.6.0 Beta 1` do resolve an issue with `pod lib lint` using Xcode 10.

### CODE REVIEW

**Comment by aamctustwo** [comment]
Codecov decrease is due to there now being a distinction in some of the `UIKit` enums between iOS and tvOS. There has been no actual difference in which functions or cases are tested.

**Comment by belenmdc** [comment]
Why is Codecov saying that test coverage has gone down so much?

**Comment by ghost** [comment]
@belenmdc Looks like it was because the Xcode test coverage reports got better with Xcode 10 or CodeCov got better at parsing them. The lines it says are no longer covered by tests had no changes to them. ¯\_(ツ)_/¯

**Review by belenmdc — APPROVED** [review]

**Comment by ghost** [comment]
Superseded by #80

**Pull request closed without merging**
